services:
  # PostgreSQL database with pgvector
  postgres:
    image: pgvector/pgvector:pg15
    container_name: crewai-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-crewai}
      POSTGRES_USER: ${POSTGRES_USER:-crewai}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - crewai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-crewai} -d ${POSTGRES_DB:-crewai}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Redis for caching and queue backend
  redis:
    image: redis:7-alpine
    container_name: crewai-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - crewai-network
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Main CrewAI Backend Application
  app:
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: production
      args:
        PYTHON_VERSION: "3.11"
    container_name: crewai-app
    environment:
      # Docker environment flag for validation
      DOCKER_ENV: "true"
      
      # Database configuration
      POSTGRES_DB: ${POSTGRES_DB:-crewai}
      POSTGRES_USER: ${POSTGRES_USER:-crewai}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      
      # Redis configuration
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      
      # Application configuration
      PROJECT_NAME: "CrewAI Backend"
      ENVIRONMENT: production
      DEBUG: "false"
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      
      # Security
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-*}
      
      # Performance
      UVICORN_WORKERS: ${UVICORN_WORKERS:-4}
      UVICORN_MAX_REQUESTS: ${UVICORN_MAX_REQUESTS:-10000}
      UVICORN_MAX_REQUESTS_JITTER: ${UVICORN_MAX_REQUESTS_JITTER:-1000}
    
    ports:
      - "${APP_PORT:-8000}:8000"
    
    volumes:
      - app_logs:/app/logs
      - app_data:/app/data
    
    networks:
      - crewai-network
    
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/readiness"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    restart: unless-stopped
    
    security_opt:
      - no-new-privileges:true
    
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
        labels: "service=crewai-app"

  # Celery Workers for background task processing
  celery-worker:
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: production
      args:
        PYTHON_VERSION: "3.11"
    container_name: crewai-celery-worker
    command: celery -A app.queue.task_queue worker --loglevel=${LOG_LEVEL:-info} --concurrency=${CELERY_WORKER_CONCURRENCY:-4} --queues=crew_execution,retry,default --max-tasks-per-child=1000
    
    environment:
      # Docker environment flag for validation
      DOCKER_ENV: "true"
      
      # Database configuration
      POSTGRES_DB: ${POSTGRES_DB:-crewai}
      POSTGRES_USER: ${POSTGRES_USER:-crewai}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      
      # Redis configuration
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      
      # Application configuration
      PROJECT_NAME: "CrewAI Backend"
      ENVIRONMENT: production
      DEBUG: "false"
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    
    volumes:
      - app_logs:/app/logs
      - celery_data:/app/data
    
    networks:
      - crewai-network
    
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    
    healthcheck:
      test: ["CMD", "celery", "-A", "app.queue.task_queue", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    restart: unless-stopped
    
    security_opt:
      - no-new-privileges:true
    
    deploy:
      replicas: ${CELERY_WORKER_REPLICAS:-1}
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'
    
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
        labels: "service=celery-worker"

  # Celery Beat for scheduled tasks
  celery-beat:
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: production
      args:
        PYTHON_VERSION: "3.11"
    container_name: crewai-celery-beat
    command: celery -A app.queue.task_queue beat --loglevel=${LOG_LEVEL:-info} --pidfile=/tmp/celerybeat.pid
    
    environment:
      # Docker environment flag for validation
      DOCKER_ENV: "true"
      
      # Database configuration
      POSTGRES_DB: ${POSTGRES_DB:-crewai}
      POSTGRES_USER: ${POSTGRES_USER:-crewai}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      
      # Redis configuration
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      
      # Application configuration
      PROJECT_NAME: "CrewAI Backend"
      ENVIRONMENT: production
      DEBUG: "false"
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    
    volumes:
      - app_logs:/app/logs
      - celery_beat_data:/app/data
    
    networks:
      - crewai-network
    
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    
    restart: unless-stopped
    
    security_opt:
      - no-new-privileges:true
    
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
    
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        labels: "service=celery-beat"

  # Flower for Celery monitoring
  flower:
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: production
      args:
        PYTHON_VERSION: "3.11"
    container_name: crewai-flower
    command: celery -A app.queue.task_queue flower --port=5555 --basic_auth=${FLOWER_USER:-admin}:${FLOWER_PASSWORD}
    
    environment:
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
      CELERY_RESULT_BACKEND: redis://:${REDIS_PASSWORD}@redis:6379/0
      FLOWER_BASIC_AUTH: ${FLOWER_USER:-admin}:${FLOWER_PASSWORD}
    
    ports:
      - "${FLOWER_PORT:-5555}:5555"
    
    networks:
      - crewai-network
    
    depends_on:
      redis:
        condition: service_healthy
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/api/workers"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    restart: unless-stopped
    
    security_opt:
      - no-new-privileges:true
    
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  app_logs:
    driver: local
  app_data:
    driver: local
  celery_data:
    driver: local
  celery_beat_data:
    driver: local

networks:
  crewai-network:
    driver: bridge
    name: crewai-production
    ipam:
      config:
        - subnet: 172.20.0.0/16 